spring:
  datasource:
    url: jdbc:mysql://localhost:3308/hot_search?characterEncoding=UTF-8
    username: root
    password: 520920
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create